[Site]
repo="shirshak55/Rust-Book-In-PDF"

[Books.The_Rust_Programming_Language]
print_url="https://doc.rust-lang.org/book/print.html"
file_name="the_rust_programming_language.pdf"

[Books.High_Assurance_Rust]
print_url="https://highassurance.rs/print.html"
file_name="high_assurance_rust.pdf"

[Books.Nomicon]
print_url="https://doc.rust-lang.org/nomicon/print.html"
file_name="nomicon.pdf"

[Books.Rust_Cookbook]
print_url="https://rust-lang-nursery.github.io/rust-cookbook/print.html"
file_name="cookbook.pdf"

[Books.RustWasm]
print_url="https://rustwasm.github.io/docs/book/print.html"
file_name="rust_wasm.pdf"
ebook_image_fallback_prefix="https://rustwasm.github.io/docs/images/"
ebook_image_fallback_base="https://raw.githubusercontent.com/rustwasm/book/master/src/images/"

[Books.EasyRust]
print_url="https://dhghomon.github.io/easy_rust/print.html"
file_name="easy_rust.pdf"
ebook_image_fallback_prefix="https://dhghomon.github.io/easy_rust/"
ebook_image_fallback_base="https://raw.githubusercontent.com/Dhghomon/easy_rust/master/"

[Books.EmbeddedRust]
print_url="https://docs.rust-embedded.org/book/print.html"
file_name="embedded_rust_book.pdf"

[Books.RustReference]
print_url="https://doc.rust-lang.org/reference/print.html"
file_name="rust_reference.pdf"

[Books.RustCLI]
print_url="https://rust-cli.github.io/book/print.html"
file_name="rust_cli.pdf"
display_title="Rust CLI"

[Books.RustByExample]
print_url="https://doc.rust-lang.org/rust-by-example/print.html"
file_name="rust_by_example.pdf"

[Books.RustFuzzBook]
print_url="https://rust-fuzz.github.io/book/print.html"
file_name="rust_fuzz.pdf"

[Books.RustPerformanceBook]
print_url="https://nnethercote.github.io/perf-book/print.html"
file_name="rust_performance.pdf"

[Books.RustDesignPatterns]
print_url="https://rust-unofficial.github.io/patterns/print.html"
file_name="rust_design_patterns.pdf"

[Books.LearnWithLinkedList]
print_url="https://rust-unofficial.github.io/too-many-lists/print.html"
file_name="rust_linked_list.pdf"


[Books.RustPractiseQuestions]
print_url="https://rust-unofficial.github.io/rust-practise-questions/print.html"
file_name="rust_practise_questions.pdf"
display_title="Rust Practise Questions"

[Books.The_Rust_Discovery-microbit]
print_url="https://docs.rust-embedded.org/discovery/microbit/print.html"
file_name="microbit_beginner_rust.pdf"
display_title="Discovery (micro:bit)"

[Books.The_Rust_DiscoverySTM]
print_url="https://docs.rust-embedded.org/discovery/f3discovery/print.html"
file_name="stm32f3discovery_beginner_rust.pdf"
display_title="Discovery (STM32F3)"

[Books.CargoBook]
print_url="https://doc.rust-lang.org/cargo/print.html"
file_name="cargo_book.pdf"

[Books.EditionGuide]
print_url="https://doc.rust-lang.org/edition-guide/print.html"
file_name="edition_guide.pdf"

[Books.RustcBook]
print_url="https://doc.rust-lang.org/rustc/print.html"
file_name="rustc_book.pdf"

[Books.RustdocBook]
print_url="https://doc.rust-lang.org/stable/rustdoc/print.html"
file_name="rustdoc_book.pdf"

[Books.RustupBook]
print_url="https://rust-lang.github.io/rustup/print.html"
file_name="rustup_book.pdf"

[Books.UnstableBook]
print_url="https://doc.rust-lang.org/unstable-book/print.html"
file_name="unstable_book.pdf"

[Books.RustRFCs]
print_url="https://rust-lang.github.io/rfcs/print.html"
file_name="rust_rfcs.pdf"
display_title="Rust RFCs"

[Books.RustAPIGuidelines]
print_url="https://rust-lang.github.io/api-guidelines/print.html"
file_name="rust_api_guidelines.pdf"

[Books.RustcDevGuide]
print_url="https://rustc-dev-guide.rust-lang.org/print.html"
file_name="rustc_dev_guide.pdf"

[Books.AsyncProgramming]
print_url="https://rust-lang.github.io/async-book/print.html"
file_name="async_programming.pdf"

[Books.UnsafeCodeGuidelines]
print_url="https://rust-lang.github.io/unsafe-code-guidelines/print.html"
file_name="unsafe_code_guidelines.pdf"

[Books.ComprehensiveRust]
print_url="https://google.github.io/comprehensive-rust/print.html"
file_name="comprehensive_rust.pdf"
display_title="Comprehensive Rust"

[Books.EffectiveRust]
print_url="https://www.lurklurk.org/effective-rust/print.html"
file_name="effective_rust.pdf"

[Books.LittleBookOfRustMacros]
print_url="https://veykril.github.io/tlborm/print.html"
file_name="rust_macros.pdf"

[Books.Embedonomicon]
print_url="https://docs.rust-embedded.org/embedonomicon/print.html"
file_name="embedonomicon.pdf"

[Books.WasmBindgenGuide]
print_url="https://wasm-bindgen.github.io/wasm-bindgen/print.html"
file_name="wasm_bindgen_guide.pdf"
ebook_image_fallback_prefix="https://wasm-bindgen.github.io/wasm-bindgen/"
ebook_image_fallback_base="https://raw.githubusercontent.com/wasm-bindgen/wasm-bindgen/main/guide/src/examples/"

[Books.LifetimeKata]
print_url="https://tfpk.github.io/lifetimekata/print.html"
file_name="lifetime_kata.pdf"
